# Generated by Django 2.0.5 on 2019-12-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=256)),
                ('emial', models.EmailField(max_length=254, null=True)),
                ('universities', models.CharField(max_length=64, null=True)),
                ('introduction', models.TextField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
